#!/usr/bin/env python
import turtle
import time
import random

delay= 0.1
wn = turtle.Screen()
wn.title("snek game by guppa")
wn.bgcolor("black")
wn.setup(width=600,height=600)
wn.tracer(0)

head = turtle.Turtle()
head.speed(6)
head.shape("square")
head.color("green")
head.penup()
head.goto(0,0)
head.direction="stop"

segments = []
#food
food = turtle.Turtle()
food.speed(6)
food.shape("circle")
food.color("red")
food.penup()
food.goto(0,100)






#functions

def move():
    if head.direction=="up":
        y=head.ycor()
        head.sety(y+20)


    if head.direction=="down":
        y=head.ycor()
        head.sety(y-20)


    if head.direction=="right":
        x=head.xcor()
        head.setx(x+20)


    if head.direction=="left":
        x=head.xcor()
        head.setx(x-20)


def go_up():
    head.direction = "up"

def go_down():
    head.direction = "down"

def go_right():
    head.direction = "right"

def go_left():
    head.direction = "left"

#keyboard bindings
wn.listen()
wn.onkeypress(go_up,"w")
wn.onkeypress(go_left,"a")
wn.onkeypress(go_down,"s")
wn.onkeypress(go_right,"d")



#main game loop
while True:

    wn.update()


    if head.distance(food) < 20:
#move food to random location
            food.goto(random.randint(-290,290),random.randint(-290,290))
         #add segment
            new_segment = turtle.Turtle()
            new_segment.speed(6)
            new_segment.shape("square")
            new_segment.color("grey")
            new_segment.penup()
            segments.append(new_segment)


    #move the end segments firwst in reverse order
    for index in range(len(segments)-1,0,-1):
        segments[index].goto(segments[index-1].xcor(),segments[index-1].ycor())
    #move segment 0 to where the head is
        if len(segments) > 0:
            segments[0].goto(head.xcor(),head.ycor())




    move()

    time.sleep(delay)


wn.mainloop()
